=== paullewallencom/nlp-java-978-1-7832-8467-2/_/src/com/lingpipe/cookbook/chapter7/tracker/entity-dictionary.dtd
<!ELEMENT dictionary (entity*,stoplist?)>
<!ATTLIST dictionary>
  
<!ELEMENT entity (alias+,non-alias*)>
<!ATTLIST entity
          id ID #REQUIRED
          type CDATA #REQUIRED   
          canonical CDATA #REQUIRED
          speculativeAliases CDATA "1">
  
<!ELEMENT alias (#PCDATA)>
<!ATTLIST alias
          xdc CDATA "1">

<!ELEMENT non-alias (#PCDATA)>

<!ELEMENT stoplist (phrase*)>

<!ELEMENT phrase (#PCDATA)>

=== paullewallencom/nlp-java-978-1-7832-8467-2/_/data/xDoc/entity-dictionary.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE dictionary PUBLIC "alias-i-entity-dictionary" "data/xDoc/entity-dictionary.dtd">
<dictionary>

<entity canonical="George W. Bush" id="1012" speculativeAliases="0" type="MALE">
  <alias xdc="1">Bush 2</alias>
  <alias xdc="1">George Walker Bush</alias>
  <alias xdc="1">George W Bush</alias>
 <alias xdc="1">George W Bush Jr.</alias>
  <alias xdc="1">George Bush</alias>
<alias xdc="1">Dubya</alias>
  <alias xdc="0">Bush</alias>
</entity>

<entity canonical="George H. W. Bush" id="1014" speculativeAliases="0" type="MALE">
  <alias xdc="1">Bush 1</alias>
  <alias xdc="1">George Herbert Walker Bush</alias>
  <alias xdc="1">George H W Bush</alias>
  <alias xdc="1">George H.W. Bush</alias>
  <alias xdc="1">George HW Bush</alias>
  <alias xdc="1">George Bush</alias>
  <alias xdc="0">Bush</alias>
</entity>

<stoplist>
  <phrase>A</phrase>
  <phrase>Finally</phrase>
</stoplist>

</dictionary>

=== paullewallencom/nlp-java-978-1-7832-8467-2/_/data/xDoc/authors-dictionary.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE dictionary PUBLIC "alias-i-entity-dictionary" "http://www.alias-i.com/dtd/entity-dictionary.dtd">
<dictionary>

<entity canonical="Breck Baldwin" id="1" speculativeAliases="0" type="MALE">
  <alias xdc="1">Breck Baldwin</alias>
  <alias xdc="1">Breckles</alias>
  <alias xdc="0">Breck</alias>
</entity>

<entity canonical="Krishna Dayanidhi" id="2" speculativeAliases="0" type="MALE">
  <alias xdc="1">Krishna Dayanidhi</alias>
  <alias xdc="1">K-Dog</alias>
  <alias xdc="0">Krishna</alias>
 
</entity>

<stoplist>
  <phrase>A</phrase>
  <phrase>Finally</phrase>
</stoplist>

</dictionary>
