=== paullewallencom/nlp-java-978-1-7832-8467-2/_/src/com/lingpipe/cookbook/chapter7/tracker/input-documents.dtd
<!ELEMENT docs (doc*)>

<!ELEMENT doc (title?,content?)>
<!ATTLIST doc
          id CDATA #REQUIRED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT content (#PCDATA)>

=== paullewallencom/nlp-java-978-1-7832-8467-2/_/data/xDoc/input/docs1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE docs
          PUBLIC "alias-i-tracker-input-documents"
          "http://www.alias-i.com/dtd/input-documents.dtd">

<docs>


<doc id="1">
<title/>
<content>
Breck Baldwin and Krishna Dayanidhi wrote a book about LingPipe. 
</content>
</doc>

<doc id="2">
<title/>
<content>
Krishna Dayanidhi is a developer. Breck Baldwin is too. 
</content>
</doc>

<doc id="3">
<title/>
<content>
K-dog likes to cook as does Breckles. 
</content>
</doc>


</docs>
